# Generated by Django 5.0.3 on 2024-03-28 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapi', '0002_book_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_name',
        ),
    ]
